package com.hopcape.domain.security.token

/**
 * Wrapper around
 * @param name
 * @param value
 * which can be attached to the JWT like
 * [TokenClaim("userId","12231")] can be attached to the
 * Token generated by [TokenService] and we then can retrieve
 * this info from the token itself*/
data class TokenClaim(
    val name: String,
    val value: String
)
